### ISSUE TITLE
crash on 64-bit platforms due to uintptr_t typedef

### ISSUE THREAD

**Issue by danadam** [Sound-Linux-More/falabaac#1]
On most 64-bit platforms a pointer size is 64-bit, while `unsigned` is 32-bit: https://en.cppreference.com/w/c/language/arithmetic_types#Data_models

The typedef in `fa_inttypes.h`:

    typedef unsigned uintptr_t;

and the usage of this `uintptr_t` like in `aacenc_init()` for example:

    uintptr_t aacenc_init(...) {
        fa_aacenc_ctx_t *f = (fa_aacenc_ctx_t *)malloc(sizeof(fa_aacenc_ctx_t));
        ...
        return (uintptr_t)f;

will chop off half of the pointer value. When such pointer is dereferenced later, it causes a crash.

**Comment by zvezdochiot** [comment]
Hi @danadam .

Yes, don't care.
